<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\autohdr.ico</ApplicationIcon>
    <StartupObject>AutoHDR.Program</StartupObject>
    <AssemblyName>AutoHDR</AssemblyName>
    <RootNamespace>AutoHDR</RootNamespace>
    <Version>1.0.5</Version>
    <Description>Automatically enable Windows HDR when games are running</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\autohdr.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Link="Assets\autohdr.ico" />
    <Content Include="Assets\autohdr.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Link="Assets\autohdr.png" />
  </ItemGroup>

</Project>
